apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
  labels:
    app: app-1
    purpose: ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1
      purpose: ingress
  # below is pod definition. pod is subset of replicaset   
  template:
    metadata:
      labels:
        app: app-1
        purpose: ingress
    spec:
      containers:
      - name: app1
        image: leelakamineni/app1:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: app-1
    purpose: ingress
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #target-port