apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    app: app2
    purpose: ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
      purpose: ingress
  # below is pod definition. pod is subset of replicaset   
  template:
    metadata:
      labels:
        app: app2
        purpose: ingress
    spec:
      containers:
      - name: app2
        image: leelakamineni/app2:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  selector:
    app: app2
    purpose: ingress
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #target-port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
    alb.ingress.kubernetes.io/group.name: albdevops #this annotation is useful to keep only one ALB under joindevops group.if you dont give this it will create another ALB.
spec:
  ingressClassName: alb
  rules:
  - host: "app2.learningdevopsaws.online" #ALB rule
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app2 # ALB Target group
            port:
              number: 80